### ISSUE TITLE
Agrega una estrofa 

### ISSUE THREAD

**Issue by Eder-Arredondo** [Eder-Arredondo/Servomecanismos-N3-Eq.5#4]
Agrega una estrofa refiriéndose a la luna y las estrellas 
 
![luna y estrellas](https://user-images.githubusercontent.com/42302773/44311534-bddfd500-a3ae-11e8-88b4-c29b3673b386.jpg)

**Comment by jorgejlmh** [comment]
agregue estrofa en #14
